### ISSUE TITLE
Cannot use the keyboard shortcuts to describe screenshot and navigator object

### ISSUE THREAD

**Issue by ogomez92** [aaclause/nvda-OpenAI#33]
Hi.
There seems to be an issue with the default text prompt when pressing NVDA+E or NVDA+O.

Apparently, the default text prompt is undefined.
I tried switching the language to English in case it was a localization problem, but no go.

Here is the traceback:
Traceback (most recent call last):
  File "scriptHandler.pyc", line 295, in executeScript
  File "C:\Users\ogome\AppData\Roaming\nvda\addons\OpenAI\globalPlugins\openai\__init__.py", line 485, in script_recognizeScreen
    (tmpPath, _("Screenshot"))
  File "gui\blockAction.pyc", line 72, in funcWrapper
  File "gui\__init__.pyc", line 216, in popupSettingsDialog
  File "C:\Users\ogome\AppData\Roaming\nvda\addons\OpenAI\globalPlugins\openai\maindialog.py", line 512, in __init__
    self.promptText.SetValue(DEFAULT_PROMPT_IMAGE_DESCRIPTION)
NameError: name 'DEFAULT_PROMPT_IMAGE_DESCRIPTION' is not defined

Let me know if you want to look at the code myself and create a PR, I'm posting it here in case I am missing something.

Thank you!

**Comment by Nael-Sayegh** [comment]
Hello,
Did you just install the extension?
Did the problem occur right from the beginning of use?
Thank you.
